### PR TITLE
Support nodejs18.x as the lambda layers are not build

### PR DESCRIPTION
**Pull request by Engerim**
* adjusted tests as new version of layers exist
* remove arm64 unsupported test for nodejs14.x in region ap as it has now support of it

### CODE REVIEW

**Review by akshaydk — APPROVED** [review]
LGTM

**Review by mrickard — APPROVED** [review]
This is great! Thank you for your contribution, @Engerim !

**Comment by mrickard** [comment]
The updated plugin will be released later today.

**Comment by mrickard** [comment]
@Engerim Version 3.4.0 should be available on npm with these changes. Thank you again!

**Pull request merged**
