### PR TITLE
Updating dependencies

### PR DESCRIPTION
**Pull request by ran-j**
Updating dependencies using npm-check-updates

### CODE REVIEW

**Comment by mrickard** [comment]
Thank you for contributing, @ran-j ! We'll review this and update you when there's a release.

**Comment by mrickard** [comment]
Thank you, @ran-j ! Would you be able to run `npm audit fix` on your branch, and update the test fixtures? (Updating the ARNs in the test fixtures would be a simple search/replace-all, and will let this pass our CI.)

**Comment by mrickard** [comment]
You could incorporate these changes for the test fixtures: https://github.com/newrelic/serverless-newrelic-lambda-layers/tree/mrickard/NR-59749/update-test-fixtures

**Comment by ran-j** [comment]
@mrickard done runing audit fix

**Review by mrickard — APPROVED** [review]
Developers who've worked on this project in the past may have to go through the process of converting Husky 4 hooks to Husky 8, but that's a local chore worth doing. 

Thank you @ran-j for the contribution!

**Comment by mrickard** [comment]
We have a couple chores on our end before this gets fully released to NPM, but we'll keep you updated.

**Pull request merged**
