### PR TITLE
feat: Added Java 21 support

### PR DESCRIPTION
**Pull request by meiao**
Adds support for using the new java 17 layer added in [newrelic/newrelic-lambda-layers#210](https://github.com/newrelic/newrelic-lambda-layers/pull/210)

### CODE REVIEW

**Review by jtduffy — APPROVED** [review]

**Review by mrickard — DISMISSED** [review]

**Comment by mrickard** [comment]
@meiao I'm not offhand sure why the CI jobs are hanging here. I may need to close/reopen the PR, which I'll do.

**Comment by mrickard** [comment]
I'll have to dig into the CirlceCI situation here.

**Comment by mrickard** [comment]
@meiao This won't unblock you for the moment, but I'd recommend bumping the version manually in package.json and the lockfile, so that release can go forward once we do unblock.

**Comment by mrickard** [comment]
@meiao Would you be able to rebase your branch against `master` and force-push? I believe I've gotten us unblocked, though I've left conflicts for you to resolve.

**Comment by meiao** [comment]
@mrickard I've rebased and updated the versions.
Now codecov/patch is failing. Not sure what I should be testing, if anything, in my changes.

**Comment by mrickard** [comment]
@meiao That's frustrating, particularly when the CodeCov diff is 0%, and the report doesn't show any specific lines. I'm going to override it.

**Review by mrickard — APPROVED** [review]

**Pull request merged**
