### PR TITLE
feat: Explain if license key fails validation

### PR DESCRIPTION
**Pull request by mrickard**
Linked issue: https://newrelic.atlassian.net/browse/LAMBDA-1003

### CODE REVIEW

**Comment by mrickard** [comment]
This also updates the serverless framework to include recent patches/fixes.

**Comment by mrickard** [comment]
Also now including a fix to remove an unnecessary license-key-checking regex at the template level.

**Review by katiewest820 — COMMENTED** [review]
I think we may want to check for the [licenseKey](https://github.com/newrelic/serverless-newrelic-lambda-layers/blob/c1d647b0611b63b1d74f3870e329faa1155c8aea/src/index.ts#L151) here too?
I saw a scenario where the wrong token was used, this call returned nothing and then the `createManagedSecret` call blew up.

**Comment by mrickard** [comment]
@katiewest820 Good point--I've added a falsy-check there now.

**Review by kolanos — APPROVED** [review]

**Review by katiewest820 — APPROVED** [review]

**Pull request merged**
