### PR TITLE
fix: Fixed query to check for log ingestion script

### LINKED ISSUE #402: Support for newrelic-log-ingestion-0356e24a3f87 naming format
#### Description

After resolving a previous issue with an old CloudFormation stack, the `serverless-newrelic-lambda-layers` plugin successfully creates a `NewRelicLogIngestion` CloudFormation stack. However, the Serverless Framework deployment still fails, reporting that it cannot find the `newrelic-log-ingestion` function and incorrectly validating the changeSet.

#### Steps to Reproduce

1. Delete any existing CloudFormation stacks that might conflict with the New Relic setup.
2. Run `sls deploy --verbose` to deploy the serverless application with the `serverless-newrelic-lambda-layers` plugin.

#### Expected Behavior

The Serverless Framework should recognize the successfully created `NewRelicLogIngestion` CloudFormation stack and complete the deployment without errors.

#### Actual Behavior

The Serverless Framework deployment fails with the following error:

```sh
✖ Could not find a `newrelic-log-ingestion` function installed.
Warning: Details about setup requirements are available here: https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/enable-new-relic-monitoring-aws-lambda#enable-process
✖ Function not found: arn:aws:lambda:us-west-2:123456789123:function:newrelic-log-ingestion
creating required newrelic-log-ingestion function in region us-west-2
✖ Unable to get stack information.
✖ { ServerlessError: Stack [NewRelicLogIngestion] already exists and cannot be created again with the changeSet [NewRelicLogIngestion-CREATE-1234567891234].
```

The error suggests that the Serverless Framework is attempting to validate a changeSet that is different from the one actually created by the CloudFormation stack.

#### Additional Information

- **Serverless Framework Version**: 3.38.0
- **Serverless-NewRelic-Lambda-Layers Plugin Version**: 5.0.0
- **NewRelic-Lambda-CLI Version**: 0.8.0
- **Operating System**: Linux
- **Stack Trace**:

```sh
✖ Could not find a `newrelic-log-ingestion` function installed.
Warning: Details about setup requirements are available here: https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/enable-new-relic-monitoring-aws-lambda#enable-process
✖ Function not found: arn:aws:lambda:us-west-2:123456789123:function:newrelic-log-ingestion
creating required newrelic-log-ingestion function in region us-west-2
✖ Unable to get stack information.
✖ { ServerlessError: Stack [NewRelicLogIngestion] already exists and cannot be created again with the changeSet [NewRelicLogIngestion-CREATE-123456789123].
      at /home/kmullaney/repos/examples/lambda/main/java/node_modules/serverless/lib/aws/request.js:221:11
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async persistentRequest (/home/kmullaney/repos/examples/lambda/main/java/node_modules/serverless/lib/aws/request.js:145:14)
    code: 'AWS_CLOUD_FORMATION_CREATE_CHANGE_SET_VALIDATION_ERROR',
    decoratedMessage: undefined,
    providerError:
     { Error [ValidationError]: Stack [NewRelicLogIngestion] already exists and cannot be created again with the changeSet [NewRelicLogIngestion-CREATE-123456789123].
         at Request.extractError (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/protocol/query.js:50:29)
         at Request.callListeners (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
         at Request.emit (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
         at Request.emit (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/request.js:686:14)
         at Request.transition (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/request.js:22:10)
         at AcceptorStateMachine.runTo (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/state_machine.js:14:12)
         at /home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/state_machine.js:26:10
         at Request.<anonymous> (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/request.js:38:9)
         at Request.<anonymous> (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/request.js:688:12)
         at Request.callListeners (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
         at Request.emit (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
         at Request.emit (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/request.js:686:14)
         at Request.transition (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/request.js:22:10)
         at AcceptorStateMachine.runTo (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/state_machine.js:14:12)
         at /home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/state_machine.js:26:10
         at Request.<anonymous> (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/request.js:38:9)
         at Request.<anonymous> (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/request.js:688:12)
         at Request.callListeners (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
         at callNextListener (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
         at IncomingMessage.onEnd (/home/kmullaney/repos/examples/lambda/main/java/node_modules/aws-sdk/lib/event_listeners.js:417:13)
         at IncomingMessage.emit (node:events:531:35)
         at IncomingMessage.emit (node:domain:488:12)
         at endReadableNT (node:internal/streams/readable:1696:12)
         at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
       code: 'ValidationError',
       time: 2024-01-20T03:52:57.928Z,
       requestId: '25aa44bd-494b-4344-b43b-b50ab62e06c3',
       statusCode: 400,
       retryable: false,
       retryDelay: 59.42190121235369 },
    providerErrorCodeExtension: 'VALIDATION_ERROR' }
```

#### Possible Solution

The `serverless-newrelic-lambda-layers` plugin may need to be updated to correctly validate the existing CloudFormation stack and its changeSet, or to properly handle the case where the `NewRelicLogIngestion` stack has already been created. Additionally, ensuring that the plugin can find the `newrelic-log-ingestion` function after it has been created might resolve the error.

#### Notes

It's looking to validate a changeSet like `NewRelicLogIngestion-CREATE-123456789123`, but the actual changeSet that was created successfully has a different series of digits on the end.

### PR DESCRIPTION
**Pull request by mrickard**
The previous check for the `newrelic-log-ingestion` function used the AWS SDK `getFunction` method, which assumes an exact match by function name. The log ingestion script is installed with a variable suffix, so an exact name match isn't possible. This change lets the plugin call `listFunctions` and iterate over the paginated results to find a looser match. 

Closes #402 
Closes NR-217218

### CODE REVIEW

**Review by jsumners-nr — COMMENTED** [review]
Is most of this moving code from one file to another? Can you highlight the changes that resolve the problem?

**Comment by mrickard** [comment]
Apologies for the large diff here. Most of the changes are indeed moving methods from `index.ts` to `integration.ts` for testability, but the operative change is this one: 

Originally in `index.ts`, the [getDestinationArn](https://github.com/newrelic/serverless-newrelic-lambda-layers/pull/403/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L878-L889) method used AWS's `getFunction`, which consistently failed to find installed ingestion functions. That approach is replaced by a call to `listFunctions` and an iteration over its paginated results in a helper function. Those methods are now in the `integration.ts` file, [here](https://github.com/newrelic/serverless-newrelic-lambda-layers/pull/403/files#diff-616b1f25a229de030f09926b82dafdc6aa0c93a00bd851f2b1f41796570fd629R461-R493).

**Review by jsumners-nr — APPROVED** [review]
Looks good to me.

**Comment by mrickard** [comment]
Sadly, the npm versioning process is still manual for this repo.

**Review by jsumners-nr — APPROVED** [review]

**Pull request merged**
